name: agent_league
description: A PropertyBox application.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  chewie: ^1.3.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.0.5
  flutter_neumorphic: ^3.2.0
  location: ^4.4.0
  syncfusion_flutter_pdfviewer: ^20.4.38
  image_picker: ^0.8.4+11
  provider: ^6.0.2
  video_player: ^2.3.0
  modal_progress_hud_nsn: ^0.3.0
  page_transition: ^2.0.5
  animations: ^2.0.2
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.3
  readmore: ^2.1.0
  fluttertoast: ^8.0.9
  file_picker: ^4.5.1
  cloud_firestore: ^4.3.0
  geolocator:
  shared_preferences: ^2.0.13
  firebase_storage: ^11.0.9
  flutter_spinkit: ^5.1.0
  flutter_document_picker: ^5.1.0
  flutter_chat_bubble: ^2.0.0
  uuid: ^3.0.6
  open_file: ^3.2.1
  url_launcher: ^6.1.2
  google_maps_place_picker_mb: ^2.0.0-mb.22
  google_place: ^0.4.7
  flutter_easyloading: ^3.0.5
  app_utils: ^0.0.4
  path_provider: ^2.0.11
  razorpay_flutter: ^1.3.0
  firebase_messaging: ^14.2.0
  flutter_local_notifications: ^12.0.4
  country_code_picker: ^2.0.2
  share_plus: ^4.0.10
  video_compress: ^3.1.0
  pie_chart:
  cached_network_image:
  timelines: ^0.1.0
  webview_flutter: ^4.0.1
 

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  tab_indicator_styler: ^2.0.0
  google_maps_flutter: ^2.1.3
  carousel_slider: ^4.0.0

flutter_native_splash:
  background_image: "assets/nativeSplash.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/pdf/
  #   - images/a_dot_ham.jpeg
  # example:
#  fonts:
#    - family: pop_md
#      fonts:
#        - asset: lib/assets/fonts/Poppins/Poppins-Medium.ttf
