// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHH4-S7eRmkVSEdMt_o4ku5IVWrpAwZnQ',
    appId: '1:36906349039:android:d82239a7c5749a60ed861a',
    messagingSenderId: '36906349039',
    projectId: 'agent-fly-a5f08',
    storageBucket: 'agent-fly-a5f08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWM_E5DpnL8bSgIB-YioFJzyDrUvszV7Q',
    appId: '1:36906349039:ios:9c832922c0d5ae0bed861a',
    messagingSenderId: '36906349039',
    projectId: 'agent-fly-a5f08',
    storageBucket: 'agent-fly-a5f08.appspot.com',
    androidClientId: '36906349039-1lhev15imfrokjkdomnncdac94h6r9ii.apps.googleusercontent.com',
    iosClientId: '36906349039-uplnq4b16ecqmcbap9604vf9ic4jk9ph.apps.googleusercontent.com',
    iosBundleId: 'com.example.agentLeague',
  );
}
